<?php

namespace Database\Seeders;

use App\Models\Company;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;

class AccountingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks for truncation
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // Truncate all tables first
        DB::table('finance_chart_of_accounts')->truncate();
        DB::table('finance_account_sub_categories')->truncate();
        DB::table('finance_account_categories')->truncate();
        DB::table('finance_account_types')->truncate();

        // Enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // Seed Account Types
        $accountTypes = [
            ['id' => 1, 'name' => 'Asset', 'slug' => 'asset', 'level' => 1, 'description' => 'Asset', 'is_default' => 'true', 'created_at' => '2023-06-21 23:15:42', 'updated_at' => '2023-06-21 23:15:42'],
            ['id' => 2, 'name' => 'Liability', 'slug' => 'liability', 'level' => 2, 'description' => 'Liability', 'is_default' => 'true', 'created_at' => '2023-06-21 23:15:42', 'updated_at' => '2023-06-21 23:15:42'],
            ['id' => 3, 'name' => 'Equity', 'slug' => 'equity', 'level' => 3, 'description' => 'Equity', 'is_default' => 'true', 'created_at' => '2023-06-21 23:15:42', 'updated_at' => '2023-06-21 23:15:42'],
            ['id' => 4, 'name' => 'Income', 'slug' => 'income', 'level' => 4, 'description' => 'Income', 'is_default' => 'true', 'created_at' => '2023-06-21 23:15:42', 'updated_at' => '2023-06-21 23:15:42'],
            ['id' => 5, 'name' => 'Expense', 'slug' => 'expense', 'level' => 5, 'description' => 'Expense', 'is_default' => 'true', 'created_at' => '2023-06-21 23:15:42', 'updated_at' => '2023-06-21 23:15:42'],
        ];
        DB::table('finance_account_types')->insert($accountTypes);

        // Seed Account Categories
        $accountCategories = [
            ['id' => 1, 'account_type_id' => 1, 'name' => 'Non-Current Assets', 'description' => 'Non-Current Assets', 'slug' => 'non-current-assets', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:23', 'updated_at' => '2023-10-11 14:54:23'],
            ['id' => 2, 'account_type_id' => 1, 'name' => 'Current Assets', 'description' => 'Current Assets', 'slug' => 'current-assets', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:23', 'updated_at' => '2023-10-11 14:54:23'],
            ['id' => 3, 'account_type_id' => 2, 'name' => 'Non-Current Liabilities', 'description' => 'Non-Current Liabilities', 'slug' => 'non-current-liabilities', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:23', 'updated_at' => '2023-10-11 14:54:23'],
            ['id' => 4, 'account_type_id' => 2, 'name' => 'Current Liabilities', 'description' => 'Current Liabilities', 'slug' => 'current-liabilities', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:23', 'updated_at' => '2023-10-11 14:54:23'],
            ['id' => 5, 'account_type_id' => 3, 'name' => 'Equity', 'description' => 'Equity', 'slug' => 'equity', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:23', 'updated_at' => '2023-10-11 14:54:23'],
            ['id' => 6, 'account_type_id' => 4, 'name' => 'Revenue', 'description' => 'Revenue', 'slug' => 'revenue', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:23', 'updated_at' => '2023-10-11 14:54:23'],
            ['id' => 7, 'account_type_id' => 5, 'name' => 'Operating Expenses', 'description' => 'Expenses', 'slug' => 'operating-expenses', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:23', 'updated_at' => '2023-10-11 14:54:23'],
            ['id' => 8, 'account_type_id' => 5, 'name' => 'Cost of Sales', 'description' => 'Cost of Sales', 'slug' => 'cost-of-sales', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:23', 'updated_at' => '2023-10-11 14:54:23'],
        ];
        DB::table('finance_account_categories')->insert($accountCategories);

        // Seed Account Sub Categories
        $accountSubCategories = [
            ['id' => 1, 'account_type_id' => 1, 'account_category_id' => 2, 'name' => 'Cash and Bank', 'slug' => 'cash-and-bank', 'ref_code' => '102001', 'description' => 'Cash and Bank', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:23', 'updated_at' => '2023-10-11 14:54:23'],
            ['id' => 2, 'account_type_id' => 1, 'account_category_id' => 2, 'name' => 'Accounts Receivable', 'slug' => 'accounts-receivable', 'ref_code' => '102002', 'description' => 'Accounts Receivable', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:23', 'updated_at' => '2023-10-11 14:54:23'],
            ['id' => 3, 'account_type_id' => 1, 'account_category_id' => 2, 'name' => 'Inventory', 'slug' => 'inventory', 'ref_code' => '102003', 'description' => 'Inventory', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:23', 'updated_at' => '2023-10-11 14:54:23'],
            ['id' => 4, 'account_type_id' => 1, 'account_category_id' => 1, 'name' => 'Property, Plant, and Equipment', 'slug' => 'property-plant-and-equipment', 'ref_code' => '101001', 'description' => 'Property, Plant, and Equipment', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:23', 'updated_at' => '2023-10-11 14:54:23'],
            ['id' => 5, 'account_type_id' => 1, 'account_category_id' => 1, 'name' => 'Investments', 'slug' => 'investments', 'ref_code' => '101002', 'description' => 'Investments', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 6, 'account_type_id' => 1, 'account_category_id' => 1, 'name' => 'Intangible Asset', 'slug' => 'intangible-asset', 'ref_code' => '101003', 'description' => 'Intangible Asset', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 7, 'account_type_id' => 2, 'account_category_id' => 4, 'name' => 'Accounts Payable', 'slug' => 'accounts-payable', 'ref_code' => '204001', 'description' => 'Accounts Payable', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 8, 'account_type_id' => 2, 'account_category_id' => 4, 'name' => 'Income Tax Payable', 'slug' => 'income-tax-payable', 'ref_code' => '204002', 'description' => 'Income Tax Payable', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 9, 'account_type_id' => 2, 'account_category_id' => 4, 'name' => 'Short-Term Loans', 'slug' => 'short-term-loans', 'ref_code' => '204003', 'description' => 'Short-Term Loans', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 10, 'account_type_id' => 2, 'account_category_id' => 3, 'name' => 'Long-Term Loans', 'slug' => 'long-term-loans', 'ref_code' => '203001', 'description' => 'Long-Term Loans', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 12, 'account_type_id' => 3, 'account_category_id' => 5, 'name' => 'Retained Earnings', 'slug' => 'retained-earnings', 'ref_code' => '305002', 'description' => 'Retained Earnings', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 13, 'account_type_id' => 4, 'account_category_id' => 6, 'name' => 'Sales', 'slug' => 'sales', 'ref_code' => '406001', 'description' => 'Sales', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 14, 'account_type_id' => 4, 'account_category_id' => 6, 'name' => 'Interest Income', 'slug' => 'interest-income', 'ref_code' => '406002', 'description' => 'Interest Income', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 15, 'account_type_id' => 4, 'account_category_id' => 6, 'name' => 'Other Income', 'slug' => 'other-income', 'ref_code' => '406003', 'description' => 'Other Income', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 17, 'account_type_id' => 5, 'account_category_id' => 7, 'name' => 'Operating Expenses', 'slug' => 'operating-expenses', 'ref_code' => '507002', 'description' => 'Operating Expenses', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 18, 'account_type_id' => 5, 'account_category_id' => 7, 'name' => 'Income Tax Expense', 'slug' => 'income-tax-expense', 'ref_code' => '507003', 'description' => 'Income Tax Expense', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 19, 'account_type_id' => 5, 'account_category_id' => 7, 'name' => 'Personnel Expenses', 'slug' => 'personnel-expense', 'ref_code' => '507004', 'description' => 'Personnel Expense', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 20, 'account_type_id' => 5, 'account_category_id' => 8, 'name' => 'Cost of Goods Sold', 'slug' => 'cost-of-sales', 'ref_code' => '508001', 'description' => 'Cost of Goods Sold', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 21, 'account_type_id' => 5, 'account_category_id' => 7, 'name' => 'Selling & Promotional Expense', 'slug' => 'selling-promotional-expense', 'ref_code' => '507005', 'description' => 'Selling & Promotional Expense', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 22, 'account_type_id' => 3, 'account_category_id' => 5, 'name' => 'Share capital', 'slug' => 'share-capital', 'ref_code' => '305003', 'description' => 'Share capital', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 23, 'account_type_id' => 3, 'account_category_id' => 5, 'name' => 'Other reserve', 'slug' => 'other-reserve', 'ref_code' => '305004', 'description' => 'Other reserve', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 24, 'account_type_id' => 3, 'account_category_id' => 5, 'name' => 'Accumulated loss', 'slug' => 'accumulated-loss', 'ref_code' => '305005', 'description' => 'Accumulated loss', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 25, 'account_type_id' => 1, 'account_category_id' => 2, 'name' => 'Prepayments and advances', 'slug' => 'prepayments-and-advances', 'ref_code' => '101004', 'description' => 'Prepayments and advances', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 26, 'account_type_id' => 5, 'account_category_id' => 7, 'name' => 'Occupancy expenses', 'slug' => 'occupancy-expenses', 'ref_code' => '507006', 'description' => 'Occupancy expenses', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 27, 'account_type_id' => 5, 'account_category_id' => 7, 'name' => 'Administrative expenses', 'slug' => 'administrative-expenses', 'ref_code' => '507007', 'description' => 'Administrative expenses', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 28, 'account_type_id' => 5, 'account_category_id' => 7, 'name' => 'Finance cost', 'slug' => 'finance-cost', 'ref_code' => '507008', 'description' => 'Finance cost', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 30, 'account_type_id' => 1, 'account_category_id' => 2, 'name' => 'Bank Guarantees', 'slug' => 'bank-guarantees', 'ref_code' => '102004', 'description' => 'Bank Guarantees', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 31, 'account_type_id' => 2, 'account_category_id' => 3, 'name' => 'Deferred Income', 'slug' => 'deferred-income', 'ref_code' => '203002', 'description' => 'Deferred Income', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 32, 'account_type_id' => 2, 'account_category_id' => 3, 'name' => 'Deposit for shares', 'slug' => 'deposit-for-shares', 'ref_code' => '203004', 'description' => 'Deposit for shares', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 33, 'account_type_id' => 1, 'account_category_id' => 2, 'name' => 'Suspense and Clearing Accounts', 'slug' => 'dsuspense-clearing-accounts', 'ref_code' => '102099', 'description' => 'Temporary accounts for holding unresolved transactions during reconciliation.', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
        ];
        DB::table('finance_account_sub_categories')->insert($accountSubCategories);


        // Seed Chart of Accounts
        $chartOfAccounts = [
            ['id' => 1, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 4, 'edited_by' => 2, 'name' => 'Building Improvements - Cost', 'currency' => NULL, 'account_number' => '1010010001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Building Improvements - Cost', 'description' => 'Building Improvements - Cost', 'slug' => 'building-improvements-cost', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:07', 'updated_at' => '2024-03-13 14:55:49',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 2, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 4, 'edited_by' => 2, 'name' => 'Office Furniture & Fittings - Cost', 'currency' => NULL, 'account_number' => '1010010002', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Office Furniture & Fittings - Cost', 'description' => 'Office Furniture & Fittings - Cost', 'slug' => 'office-furniture-fittings-cost', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:07', 'updated_at' => '2024-03-13 14:55:49',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 3, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 4, 'edited_by' => 2, 'name' => 'Office Equipments - Cost', 'currency' => NULL, 'account_number' => '1010010003', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Office Equipments - Cost', 'description' => 'Office Equipments - Cost', 'slug' => 'office-equipments-cost', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:07', 'updated_at' => '2024-03-13 14:55:49',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 4, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 4, 'edited_by' => 2, 'name' => 'Computer & IT equipments - Cost', 'currency' => NULL, 'account_number' => '1010010004', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Computer & IT equipments - Cost', 'description' => 'Computer & IT equipments - Cost', 'slug' => 'computer-it-equipments-cost', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:07', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 5, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 4, 'edited_by' => 2, 'name' => 'Motor Vehicles - Cost', 'currency' => NULL, 'account_number' => '1010010005', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Motor Vehicles - Cost', 'description' => 'Motor Vehicles - Cost', 'slug' => 'motor-vehicles-cost', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:07', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 6, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 4, 'edited_by' => 2, 'name' => 'Capital Work-in-progress - Cost', 'currency' => NULL, 'account_number' => '1010010006', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Capital Work-in-progress - Cost', 'description' => 'Capital Work-in-progress - Cost', 'slug' => 'capital-work-in-progress-cost', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:07', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 7, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 4, 'edited_by' => 2, 'name' => 'Building Improvements - Accumulated Depreciation', 'currency' => NULL, 'account_number' => '1010010007', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Building Improvements - Accumulated Depreciation', 'description' => 'Building Improvements - Accumulated Depreciation', 'slug' => 'building-improvements-accumulated-depreciation', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:07', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 8, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 4, 'edited_by' => 2, 'name' => 'Office Furniture & Fittings - Accumulated Depreciation', 'currency' => NULL, 'account_number' => '1010010008', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Office Furniture & Fittings - Accumulated Depreciation', 'description' => 'Office Furniture & Fittings - Accumulated Depreciation', 'slug' => 'office-furniture-fittings-accumulated-depreciation', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:07', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 9, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 4, 'edited_by' => 2, 'name' => 'Office Equipments - Accumulated Depreciation', 'currency' => NULL, 'account_number' => '1010010009', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Office Equipments - Accumulated Depreciation', 'description' => 'Office Equipments - Accumulated Depreciation', 'slug' => 'office-equipments-accumulated-depreciation', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:07', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 10, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 4, 'edited_by' => 2, 'name' => 'Computer & IT equipments - Accumulated Depreciation', 'currency' => NULL, 'account_number' => '1010010010', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Computer & IT equipments - Accumulated Depreciation', 'description' => 'Computer & IT equipments - Accumulated Depreciation', 'slug' => 'computer-it-equipments-accumulated-depreciation', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:07', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 11, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 4, 'edited_by' => 2, 'name' => 'Motor Vehicle - Accumulated Depreciation', 'currency' => NULL, 'account_number' => '1010010011', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Motor Vehicle - Accumulated Depreciation', 'description' => 'Motor Vehicle - Accumulated Depreciation', 'slug' => 'motor-vehicle-accumulated-depreciation', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:07', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 12, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 6, 'edited_by' => 2, 'name' => 'Softwares', 'currency' => NULL, 'account_number' => '1010030001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Softwares', 'description' => 'Softwares', 'slug' => 'softwares', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:07', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 13, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 6, 'edited_by' => 2, 'name' => 'Softwares - accumulated amortization', 'currency' => NULL, 'account_number' => '1010030002', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Softwares - accumulated amortization', 'description' => 'Softwares - accumulated amortization', 'slug' => 'softwares-accumulated-amortization', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 14, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 30, 'edited_by' => 2, 'name' => 'Bank Guarantees', 'currency' => NULL, 'account_number' => '1010040001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Bank Guarantees', 'description' => 'Bank Guarantees', 'slug' => 'bank-guarantees', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 15, 'account_type_id' => 1, 'account_category_id' => 2, 'account_sub_category_id' => 3, 'edited_by' => 2, 'name' => 'Inventories', 'currency' => NULL, 'account_number' => '1020030001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Inventories', 'description' => 'Inventories', 'slug' => 'inventories', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 16, 'account_type_id' => 1, 'account_category_id' => 2, 'account_sub_category_id' => 3, 'edited_by' => 2, 'name' => 'Inventories In-transit', 'currency' => NULL, 'account_number' => '1020030002', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Inventories In-transit', 'description' => 'Inventories In-transit', 'slug' => 'inventories-in-transit', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 17, 'account_type_id' => 1, 'account_category_id' => 2, 'account_sub_category_id' => 25, 'edited_by' => 2, 'name' => 'Prepaid Rent', 'currency' => NULL, 'account_number' => '1020040001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Prepaid Rent', 'description' => 'Prepaid Rent', 'slug' => 'prepaid-rent', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 18, 'account_type_id' => 1, 'account_category_id' => 2, 'account_sub_category_id' => 25, 'edited_by' => 2, 'name' => 'Prepaid Insurance', 'currency' => NULL, 'account_number' => '1020040002', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Prepaid Insurance', 'description' => 'Prepaid Insurance', 'slug' => 'prepaid-insurance', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 19, 'account_type_id' => 1, 'account_category_id' => 2, 'account_sub_category_id' => 25, 'edited_by' => 2, 'name' => 'Other Prepayments', 'currency' => NULL, 'account_number' => '1020040003', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Other Prepayments', 'description' => 'Other Prepayments', 'slug' => 'other-prepayments', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 20, 'account_type_id' => 1, 'account_category_id' => 2, 'account_sub_category_id' => 1, 'edited_by' => 2, 'name' => 'Supplier Advances', 'currency' => NULL, 'account_number' => '1020010001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Supplier Advances', 'description' => 'Supplier Advances', 'slug' => 'supplier-advances', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 21, 'account_type_id' => 1, 'account_category_id' => 2, 'account_sub_category_id' => 2, 'edited_by' => 2, 'name' => 'Trade Account Receivables', 'currency' => NULL, 'account_number' => '1020020001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Trade Account Receivables', 'description' => 'Trade Account Receivables', 'slug' => 'trade-account-receivables', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 22, 'account_type_id' => 1, 'account_category_id' => 2, 'account_sub_category_id' => 2, 'edited_by' => 2, 'name' => 'Sundry Debtors', 'currency' => NULL, 'account_number' => '1020020002', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Sundry Debtors', 'description' => 'Sundry Debtors', 'slug' => 'sundry-debtors', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 23, 'account_type_id' => 1, 'account_category_id' => 2, 'account_sub_category_id' => 2, 'edited_by' => 2, 'name' => 'Staff Advances', 'currency' => NULL, 'account_number' => '1020020003', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Staff Advances', 'description' => 'Staff Advances', 'slug' => 'staff-advances', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 24, 'account_type_id' => 1, 'account_category_id' => 2, 'account_sub_category_id' => 2, 'edited_by' => 2, 'name' => 'Input VAT', 'currency' => NULL, 'account_number' => '1020020004', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Input VAT', 'description' => 'Input VAT', 'slug' => 'input-vat', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 25, 'account_type_id' => 1, 'account_category_id' => 2, 'account_sub_category_id' => 2, 'edited_by' => 2, 'name' => 'WHT receivables', 'currency' => NULL, 'account_number' => '1020020005', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'WHT receivables', 'description' => 'WHT receivables', 'slug' => 'wht-receivables', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 26, 'account_type_id' => 1, 'account_category_id' => 2, 'account_sub_category_id' => 2, 'edited_by' => 2, 'name' => 'Due from Shareholders', 'currency' => NULL, 'account_number' => '1020020006', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Due from Shareholders', 'description' => 'Due from Shareholders', 'slug' => 'due-from-shareholders', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 27, 'account_type_id' => 2, 'account_category_id' => 3, 'account_sub_category_id' => 10, 'edited_by' => 2, 'name' => 'Expected Credit loss', 'currency' => NULL, 'account_number' => '2030010001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Expected Credit loss', 'description' => 'Expected Credit loss', 'slug' => 'expected-credit-loss', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 28, 'account_type_id' => 2, 'account_category_id' => 4, 'account_sub_category_id' => 7, 'edited_by' => 2, 'name' => 'Rent Payable', 'currency' => NULL, 'account_number' => '2040010001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Rent Payable', 'description' => 'Rent Payable', 'slug' => 'rent-payable', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 29, 'account_type_id' => 2, 'account_category_id' => 4, 'account_sub_category_id' => 7, 'edited_by' => 2, 'name' => 'Service Charge Payable', 'currency' => NULL, 'account_number' => '2040010002', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Service Charge Payable', 'description' => 'Service Charge Payable', 'slug' => 'service-charge-payable', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 30, 'account_type_id' => 2, 'account_category_id' => 4, 'account_sub_category_id' => 7, 'edited_by' => 2, 'name' => 'Utilities Payable', 'currency' => NULL, 'account_number' => '2040010003', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Utilities Payable', 'description' => 'Utilities Payable', 'slug' => 'utilities-payable', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 31, 'account_type_id' => 2, 'account_category_id' => 4, 'account_sub_category_id' => 7, 'edited_by' => 2, 'name' => 'Other Payables', 'currency' => NULL, 'account_number' => '2040010004', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Other Payables', 'description' => 'Other Payables', 'slug' => 'other-payables', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 32, 'account_type_id' => 2, 'account_category_id' => 4, 'account_sub_category_id' => 7, 'edited_by' => 2, 'name' => 'Salaries Payable', 'currency' => NULL, 'account_number' => '2040010005', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Salaries Payable', 'description' => 'Salaries Payable', 'slug' => 'salaries-payable', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 33, 'account_type_id' => 2, 'account_category_id' => 4, 'account_sub_category_id' => 7, 'edited_by' => 2, 'name' => 'PAYE Payable', 'currency' => NULL, 'account_number' => '2040010006', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'PAYE Payable', 'description' => 'PAYE Payable', 'slug' => 'paye-payable', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 34, 'account_type_id' => 2, 'account_category_id' => 4, 'account_sub_category_id' => 7, 'edited_by' => 2, 'name' => 'Pension Payable', 'currency' => NULL, 'account_number' => '2040010007', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Pension Payable', 'description' => 'Pension Payable', 'slug' => 'pension-payable', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 35, 'account_type_id' => 2, 'account_category_id' => 4, 'account_sub_category_id' => 7, 'edited_by' => 2, 'name' => 'VAT Payable', 'currency' => NULL, 'account_number' => '2040010008', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'VAT Payable', 'description' => 'VAT Payable', 'slug' => 'vat-payable', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 36, 'account_type_id' => 2, 'account_category_id' => 4, 'account_sub_category_id' => 7, 'edited_by' => 2, 'name' => 'Withholding Tax Payable - Federal', 'currency' => NULL, 'account_number' => '2040010009', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Withholding Tax Payable - Federal', 'description' => 'Withholding Tax Payable - Federal', 'slug' => 'withholding-tax-payable-federal', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 37, 'account_type_id' => 2, 'account_category_id' => 4, 'account_sub_category_id' => 7, 'edited_by' => 2, 'name' => 'Withholding Tax Payable - States', 'currency' => NULL, 'account_number' => '2040010010', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Withholding Tax Payable - States', 'description' => 'Withholding Tax Payable - States', 'slug' => 'withholding-tax-payable-states', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 38, 'account_type_id' => 2, 'account_category_id' => 4, 'account_sub_category_id' => 8, 'edited_by' => 2, 'name' => 'Company Income Tax Payable', 'currency' => NULL, 'account_number' => '2040020001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Company Income Tax Payable', 'description' => 'Company Income Tax Payable', 'slug' => 'company-income-tax-payable', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 39, 'account_type_id' => 2, 'account_category_id' => 4, 'account_sub_category_id' => 7, 'edited_by' => 2, 'name' => 'Trade Accounts Payable', 'currency' => NULL, 'account_number' => '2040010011', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Trade Accounts Payable', 'description' => 'Trade Accounts Payable', 'slug' => 'trade-accounts-payable', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 40, 'account_type_id' => 3, 'account_category_id' => 5, 'account_sub_category_id' => 22, 'edited_by' => 2, 'name' => 'Share Capital', 'currency' => NULL, 'account_number' => '3050030001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Share Capital', 'description' => 'Share Capital', 'slug' => 'share-capital', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 41, 'account_type_id' => 3, 'account_category_id' => 5, 'account_sub_category_id' => 12, 'edited_by' => 2, 'name' => 'Retained Earnings', 'currency' => NULL, 'account_number' => '3050050001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Retained Earnings', 'description' => 'Retained Earnings', 'slug' => 'retained-earnings', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 42, 'account_type_id' => 3, 'account_category_id' => 5, 'account_sub_category_id' => 23, 'edited_by' => 2, 'name' => 'Other Reserves', 'currency' => NULL, 'account_number' => '3050000000', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Other Reserves', 'description' => 'Other Reserves', 'slug' => 'other-reserves', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 43, 'account_type_id' => 4, 'account_category_id' => 6, 'account_sub_category_id' => 13, 'edited_by' => 2, 'name' => 'Sales Proceeds', 'currency' => NULL, 'account_number' => '4060010001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Sales Proceeds', 'description' => 'Sales Proceeds', 'slug' => 'sales-proceeds', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 44, 'account_type_id' => 4, 'account_category_id' => 6, 'account_sub_category_id' => 13, 'edited_by' => 2, 'name' => 'Sales', 'currency' => NULL, 'account_number' => '4060010002', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Sales', 'description' => 'Sales', 'slug' => 'sales', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 45, 'account_type_id' => 4, 'account_category_id' => 6, 'account_sub_category_id' => 13, 'edited_by' => 2, 'name' => 'Discounts', 'currency' => NULL, 'account_number' => '4060010003', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Discounts', 'description' => 'Discounts', 'slug' => 'discounts', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 46, 'account_type_id' => 4, 'account_category_id' => 6, 'account_sub_category_id' => 13, 'edited_by' => 2, 'name' => 'Sales return', 'currency' => NULL, 'account_number' => '4060010004', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Sales return', 'description' => 'Sales return', 'slug' => 'sales-return', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 47, 'account_type_id' => 4, 'account_category_id' => 6, 'account_sub_category_id' => 15, 'edited_by' => 2, 'name' => 'Other Income', 'currency' => NULL, 'account_number' => '4060030001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Other Income', 'description' => 'Other Income', 'slug' => 'other-income', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 48, 'account_type_id' => 4, 'account_category_id' => 6, 'account_sub_category_id' => 15, 'edited_by' => 2, 'name' => 'Profit on disposal of assets', 'currency' => NULL, 'account_number' => '4060030002', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Profit on disposal of assets', 'description' => 'Profit on disposal of assets', 'slug' => 'profit-on-disposal-of-assets', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 49, 'account_type_id' => 4, 'account_category_id' => 6, 'account_sub_category_id' => 15, 'edited_by' => 2, 'name' => 'Interests on short term deposits', 'currency' => NULL, 'account_number' => '4060030003', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Interests on short term deposits', 'description' => 'Interests on short term deposits', 'slug' => 'interests-on-short-term-deposits', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 50, 'account_type_id' => 5, 'account_category_id' => 7, 'account_sub_category_id' => 28, 'edited_by' => 2, 'name' => 'Unrealised exchange gain', 'currency' => NULL, 'account_number' => '5070080001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Unrealised exchange gain', 'description' => 'Unrealised exchange gain', 'slug' => 'unrealised-exchange-gain', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 51, 'account_type_id' => 5, 'account_category_id' => 7, 'account_sub_category_id' => 28, 'edited_by' => 2, 'name' => 'Realised exchange gain', 'currency' => NULL, 'account_number' => '5070080002', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Realised exchange gain', 'description' => 'Realised exchange gain', 'slug' => 'realised-exchange-gain', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 52, 'account_type_id' => 5, 'account_category_id' => 8, 'account_sub_category_id' => 20, 'edited_by' => 2, 'name' => 'Cost of Goods Sold', 'currency' => NULL, 'account_number' => '5080010001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Cost of Goods Sold', 'description' => 'Cost of Goods Sold', 'slug' => 'cost-of-goods-sold', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 53, 'account_type_id' => 5, 'account_category_id' => 8, 'account_sub_category_id' => 20, 'edited_by' => 2, 'name' => 'Freight costs', 'currency' => NULL, 'account_number' => '5080010002', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Freight costs', 'description' => 'Freight costs', 'slug' => 'freight-costs', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 54, 'account_type_id' => 5, 'account_category_id' => 8, 'account_sub_category_id' => 20, 'edited_by' => 2, 'name' => 'Inventory write offs / write downs', 'currency' => NULL, 'account_number' => '5080010003', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Inventory write offs / write downs', 'description' => 'Inventory write offs / write downs', 'slug' => 'inventory-write-offs-write-downs', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 55, 'account_type_id' => 5, 'account_category_id' => 7, 'account_sub_category_id' => 19, 'edited_by' => 2, 'name' => 'Staff Costs', 'currency' => NULL, 'account_number' => '5070040001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Staff Costs', 'description' => 'Staff Costs', 'slug' => 'staff-costs', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 56, 'account_type_id' => 5, 'account_category_id' => 7, 'account_sub_category_id' => 19, 'edited_by' => 2, 'name' => 'Salaries & Wages - Other Allowances', 'currency' => NULL, 'account_number' => '5070040002', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Salaries & Wages - Other Allowances', 'description' => 'Salaries & Wages - Other Allowances', 'slug' => 'salaries-wages-other-allowances', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 57, 'account_type_id' => 5, 'account_category_id' => 7, 'account_sub_category_id' => 19, 'edited_by' => 2, 'name' => "Employer's contribution to pension", 'currency' => NULL, 'account_number' => '5070040003', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => "Employer's contribution to pension", 'description' => "Employer's contribution to pension", 'slug' => 'employers-contribution-to-pension', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 58, 'account_type_id' => 5, 'account_category_id' => 7, 'account_sub_category_id' => 26, 'edited_by' => 2, 'name' => 'Rents', 'currency' => NULL, 'account_number' => '5070060001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Rents', 'description' => 'Rents', 'slug' => 'rents', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 59, 'account_type_id' => 5, 'account_category_id' => 7, 'account_sub_category_id' => 26, 'edited_by' => 2, 'name' => 'Service Charges', 'currency' => NULL, 'account_number' => '5070060002', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Service Charges', 'description' => 'Service Charges', 'slug' => 'service-charges', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 60, 'account_type_id' => 5, 'account_category_id' => 7, 'account_sub_category_id' => 26, 'edited_by' => 2, 'name' => 'Utilities', 'currency' => NULL, 'account_number' => '5070060003', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Utilities', 'description' => 'Utilities', 'slug' => 'utilities', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 61, 'account_type_id' => 5, 'account_category_id' => 7, 'account_sub_category_id' => 27, 'edited_by' => 2, 'name' => 'Repairs and maintenance', 'currency' => NULL, 'account_number' => '5070070001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Repairs and maintenance', 'description' => 'Repairs and maintenance', 'slug' => 'repairs-and-maintenance', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 62, 'account_type_id' => 5, 'account_category_id' => 7, 'account_sub_category_id' => 27, 'edited_by' => 2, 'name' => 'Directors fees', 'currency' => NULL, 'account_number' => '5070070002', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Directors fees', 'description' => 'Directors fees', 'slug' => 'directors-fees', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 63, 'account_type_id' => 5, 'account_category_id' => 7, 'account_sub_category_id' => 27, 'edited_by' => 2, 'name' => 'Audit fees', 'currency' => NULL, 'account_number' => '5070070003', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Audit fees', 'description' => 'Audit fees', 'slug' => 'audit-fees', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 64, 'account_type_id' => 5, 'account_category_id' => 7, 'account_sub_category_id' => 27, 'edited_by' => 2, 'name' => 'Professional fees', 'currency' => NULL, 'account_number' => '5070070004', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Professional fees', 'description' => 'Professional fees', 'slug' => 'professional-fees', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 65, 'account_type_id' => 5, 'account_category_id' => 7, 'account_sub_category_id' => 27, 'edited_by' => 2, 'name' => 'Bank charges', 'currency' => NULL, 'account_number' => '5070070005', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Bank charges', 'description' => 'Bank charges', 'slug' => 'bank-charges', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 66, 'account_type_id' => 5, 'account_category_id' => 7, 'account_sub_category_id' => 27, 'edited_by' => 2, 'name' => 'Internet connection & hosting', 'currency' => NULL, 'account_number' => '5070070006', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Internet connection & hosting', 'description' => 'Internet connection & hosting', 'slug' => 'internet-connection-hosting', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 67, 'account_type_id' => 5, 'account_category_id' => 7, 'account_sub_category_id' => 18, 'edited_by' => 2, 'name' => 'Company income tax', 'currency' => NULL, 'account_number' => '5070030001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Company income tax', 'description' => 'Company income tax', 'slug' => 'company-income-tax', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 68, 'account_type_id' => 5, 'account_category_id' => 7, 'account_sub_category_id' => 27, 'edited_by' => 2, 'name' => 'Depreciation expense', 'currency' => NULL, 'account_number' => '5070070007', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Depreciation expense', 'description' => 'Depreciation expense', 'slug' => 'depreciation-expense', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 69, 'account_type_id' => 5, 'account_category_id' => 7, 'account_sub_category_id' => 27, 'edited_by' => 2, 'name' => 'Amortisation expense', 'currency' => NULL, 'account_number' => '5070070008', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Amortisation expense', 'description' => 'Amortisation expense', 'slug' => 'amortisation-expense', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 70, 'account_type_id' => 1, 'account_category_id' => 2, 'account_sub_category_id' => 33, 'edited_by' => 2, 'name' => 'Suspense Account', 'currency' => NULL, 'account_number' => '1020020007', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Suspense Account', 'description' => 'Suspense Account', 'slug' => 'suspense-account', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
        //add account payable and some bank and cash
        
        ];

        DB::table('finance_chart_of_accounts')->insert($chartOfAccounts);
    }
}
