<?php

namespace Database\Seeders;

use App\Models\Company;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;

class AccountingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks for truncation
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // Truncate all tables first
        DB::table('finance_chart_of_accounts')->truncate();
        DB::table('finance_account_sub_categories')->truncate();
        DB::table('finance_account_categories')->truncate();
        DB::table('finance_account_types')->truncate();

        // Enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // Seed Account Types
        $accountTypes = [
            ['id' => 1, 'name' => 'Asset', 'slug' => 'asset', 'level' => 1, 'description' => 'Asset', 'is_default' => 'true', 'created_at' => '2023-06-21 23:15:42', 'updated_at' => '2023-06-21 23:15:42'],
            ['id' => 2, 'name' => 'Liability', 'slug' => 'liability', 'level' => 2, 'description' => 'Liability', 'is_default' => 'true', 'created_at' => '2023-06-21 23:15:42', 'updated_at' => '2023-06-21 23:15:42'],
            ['id' => 3, 'name' => 'Equity', 'slug' => 'equity', 'level' => 3, 'description' => 'Equity', 'is_default' => 'true', 'created_at' => '2023-06-21 23:15:42', 'updated_at' => '2023-06-21 23:15:42'],
            ['id' => 4, 'name' => 'Income', 'slug' => 'income', 'level' => 4, 'description' => 'Income', 'is_default' => 'true', 'created_at' => '2023-06-21 23:15:42', 'updated_at' => '2023-06-21 23:15:42'],
            ['id' => 5, 'name' => 'Expense', 'slug' => 'expense', 'level' => 5, 'description' => 'Expense', 'is_default' => 'true', 'created_at' => '2023-06-21 23:15:42', 'updated_at' => '2023-06-21 23:15:42'],
        ];
        DB::table('finance_account_types')->insert($accountTypes);

        // Seed Account Categories
        $accountCategories = [
            ['id' => 1, 'account_type_id' => 1, 'name' => 'Non-Current Assets', 'description' => 'Non-Current Assets', 'slug' => 'non-current-assets', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:23', 'updated_at' => '2023-10-11 14:54:23'],
            ['id' => 2, 'account_type_id' => 1, 'name' => 'Current Assets', 'description' => 'Current Assets', 'slug' => 'current-assets', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:23', 'updated_at' => '2023-10-11 14:54:23'],
            ['id' => 3, 'account_type_id' => 2, 'name' => 'Non-Current Liabilities', 'description' => 'Non-Current Liabilities', 'slug' => 'non-current-liabilities', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:23', 'updated_at' => '2023-10-11 14:54:23'],
            ['id' => 4, 'account_type_id' => 2, 'name' => 'Current Liabilities', 'description' => 'Current Liabilities', 'slug' => 'current-liabilities', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:23', 'updated_at' => '2023-10-11 14:54:23'],
            ['id' => 5, 'account_type_id' => 3, 'name' => 'Equity', 'description' => 'Equity', 'slug' => 'equity', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:23', 'updated_at' => '2023-10-11 14:54:23'],
            ['id' => 6, 'account_type_id' => 4, 'name' => 'Revenue', 'description' => 'Revenue', 'slug' => 'revenue', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:23', 'updated_at' => '2023-10-11 14:54:23'],
            ['id' => 7, 'account_type_id' => 5, 'name' => 'Operating Expenses', 'description' => 'Expenses', 'slug' => 'operating-expenses', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:23', 'updated_at' => '2023-10-11 14:54:23'],
            ['id' => 8, 'account_type_id' => 5, 'name' => 'Cost of Sales', 'description' => 'Cost of Sales', 'slug' => 'cost-of-sales', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:23', 'updated_at' => '2023-10-11 14:54:23'],
        ];
        DB::table('finance_account_categories')->insert($accountCategories);

        // Seed Account Sub Categories
        $accountSubCategories = [
            ['id' => 1, 'account_type_id' => 1, 'account_category_id' => 2, 'name' => 'Cash and Bank', 'slug' => 'cash-and-bank', 'ref_code' => '102001', 'description' => 'Cash and Bank', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:23', 'updated_at' => '2023-10-11 14:54:23'],
            ['id' => 2, 'account_type_id' => 1, 'account_category_id' => 2, 'name' => 'Accounts Receivable', 'slug' => 'accounts-receivable', 'ref_code' => '102002', 'description' => 'Accounts Receivable', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:23', 'updated_at' => '2023-10-11 14:54:23'],
            ['id' => 3, 'account_type_id' => 1, 'account_category_id' => 2, 'name' => 'Inventory', 'slug' => 'inventory', 'ref_code' => '102003', 'description' => 'Inventory', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:23', 'updated_at' => '2023-10-11 14:54:23'],
            ['id' => 4, 'account_type_id' => 1, 'account_category_id' => 1, 'name' => 'Property, Plant, and Equipment', 'slug' => 'property-plant-and-equipment', 'ref_code' => '101001', 'description' => 'Property, Plant, and Equipment', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:23', 'updated_at' => '2023-10-11 14:54:23'],
            ['id' => 5, 'account_type_id' => 1, 'account_category_id' => 1, 'name' => 'Investments', 'slug' => 'investments', 'ref_code' => '101002', 'description' => 'Investments', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 6, 'account_type_id' => 1, 'account_category_id' => 1, 'name' => 'Intangible Asset', 'slug' => 'intangible-asset', 'ref_code' => '101003', 'description' => 'Intangible Asset', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 7, 'account_type_id' => 2, 'account_category_id' => 4, 'name' => 'Accounts Payable', 'slug' => 'accounts-payable', 'ref_code' => '204001', 'description' => 'Accounts Payable', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 8, 'account_type_id' => 2, 'account_category_id' => 4, 'name' => 'Income Tax Payable', 'slug' => 'income-tax-payable', 'ref_code' => '204002', 'description' => 'Income Tax Payable', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 9, 'account_type_id' => 2, 'account_category_id' => 4, 'name' => 'Short-Term Loans', 'slug' => 'short-term-loans', 'ref_code' => '204003', 'description' => 'Short-Term Loans', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 10, 'account_type_id' => 2, 'account_category_id' => 3, 'name' => 'Long-Term Loans', 'slug' => 'long-term-loans', 'ref_code' => '203001', 'description' => 'Long-Term Loans', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 12, 'account_type_id' => 3, 'account_category_id' => 5, 'name' => 'Retained Earnings', 'slug' => 'retained-earnings', 'ref_code' => '305002', 'description' => 'Retained Earnings', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 13, 'account_type_id' => 4, 'account_category_id' => 6, 'name' => 'Sales', 'slug' => 'sales', 'ref_code' => '406001', 'description' => 'Sales', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 14, 'account_type_id' => 4, 'account_category_id' => 6, 'name' => 'Interest Income', 'slug' => 'interest-income', 'ref_code' => '406002', 'description' => 'Interest Income', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 15, 'account_type_id' => 4, 'account_category_id' => 6, 'name' => 'Other Income', 'slug' => 'other-income', 'ref_code' => '406003', 'description' => 'Other Income', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 17, 'account_type_id' => 5, 'account_category_id' => 7, 'name' => 'Operating Expenses', 'slug' => 'operating-expenses', 'ref_code' => '507002', 'description' => 'Operating Expenses', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 18, 'account_type_id' => 5, 'account_category_id' => 7, 'name' => 'Income Tax Expense', 'slug' => 'income-tax-expense', 'ref_code' => '507003', 'description' => 'Income Tax Expense', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 19, 'account_type_id' => 5, 'account_category_id' => 7, 'name' => 'Personnel Expenses', 'slug' => 'personnel-expense', 'ref_code' => '507004', 'description' => 'Personnel Expense', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 20, 'account_type_id' => 5, 'account_category_id' => 8, 'name' => 'Cost of Goods Sold', 'slug' => 'cost-of-sales', 'ref_code' => '508001', 'description' => 'Cost of Goods Sold', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 21, 'account_type_id' => 5, 'account_category_id' => 7, 'name' => 'Selling & Promotional Expense', 'slug' => 'selling-promotional-expense', 'ref_code' => '507005', 'description' => 'Selling & Promotional Expense', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 22, 'account_type_id' => 3, 'account_category_id' => 5, 'name' => 'Share capital', 'slug' => 'share-capital', 'ref_code' => '305003', 'description' => 'Share capital', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 23, 'account_type_id' => 3, 'account_category_id' => 5, 'name' => 'Other reserve', 'slug' => 'other-reserve', 'ref_code' => '305004', 'description' => 'Other reserve', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 24, 'account_type_id' => 3, 'account_category_id' => 5, 'name' => 'Accumulated loss', 'slug' => 'accumulated-loss', 'ref_code' => '305005', 'description' => 'Accumulated loss', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 25, 'account_type_id' => 1, 'account_category_id' => 2, 'name' => 'Prepayments and advances', 'slug' => 'prepayments-and-advances', 'ref_code' => '101004', 'description' => 'Prepayments and advances', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 26, 'account_type_id' => 5, 'account_category_id' => 7, 'name' => 'Occupancy expenses', 'slug' => 'occupancy-expenses', 'ref_code' => '507006', 'description' => 'Occupancy expenses', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 27, 'account_type_id' => 5, 'account_category_id' => 7, 'name' => 'Administrative expenses', 'slug' => 'administrative-expenses', 'ref_code' => '507007', 'description' => 'Administrative expenses', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 28, 'account_type_id' => 5, 'account_category_id' => 7, 'name' => 'Finance cost', 'slug' => 'finance-cost', 'ref_code' => '507008', 'description' => 'Finance cost', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 30, 'account_type_id' => 1, 'account_category_id' => 2, 'name' => 'Bank Guarantees', 'slug' => 'bank-guarantees', 'ref_code' => '102004', 'description' => 'Bank Guarantees', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 31, 'account_type_id' => 2, 'account_category_id' => 3, 'name' => 'Deferred Income', 'slug' => 'deferred-income', 'ref_code' => '203002', 'description' => 'Deferred Income', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
            ['id' => 32, 'account_type_id' => 2, 'account_category_id' => 3, 'name' => 'Deposit for shares', 'slug' => 'deposit-for-shares', 'ref_code' => '203004', 'description' => 'Deposit for shares', 'is_default' => 'true', 'created_at' => '2023-10-11 14:54:24', 'updated_at' => '2023-10-11 14:54:24'],
        ];
        DB::table('finance_account_sub_categories')->insert($accountSubCategories);


        // Seed Chart of Accounts
        $chartOfAccounts = [
            ['id' => 1, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 4, 'edited_by' => 2, 'name' => 'Building Improvements - Cost', 'currency' => NULL, 'account_number' => '1010010001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Building Improvements - Cost', 'description' => 'Building Improvements - Cost', 'slug' => 'building-improvements-cost', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:07', 'updated_at' => '2024-03-13 14:55:49',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 2, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 4, 'edited_by' => 2, 'name' => 'Office Furniture & Fittings - Cost', 'currency' => NULL, 'account_number' => '1010010002', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Office Furniture & Fittings - Cost', 'description' => 'Office Furniture & Fittings - Cost', 'slug' => 'office-furniture-fittings-cost', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:07', 'updated_at' => '2024-03-13 14:55:49',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 3, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 4, 'edited_by' => 2, 'name' => 'Office Equipments - Cost', 'currency' => NULL, 'account_number' => '1010010003', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Office Equipments - Cost', 'description' => 'Office Equipments - Cost', 'slug' => 'office-equipments-cost', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:07', 'updated_at' => '2024-03-13 14:55:49',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 4, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 4, 'edited_by' => 2, 'name' => 'Computer & IT equipments - Cost', 'currency' => NULL, 'account_number' => '1010010004', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Computer & IT equipments - Cost', 'description' => 'Computer & IT equipments - Cost', 'slug' => 'computer-it-equipments-cost', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:07', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 5, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 4, 'edited_by' => 2, 'name' => 'Motor Vehicles - Cost', 'currency' => NULL, 'account_number' => '1010010005', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Motor Vehicles - Cost', 'description' => 'Motor Vehicles - Cost', 'slug' => 'motor-vehicles-cost', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:07', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 6, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 4, 'edited_by' => 2, 'name' => 'Capital Work-in-progress - Cost', 'currency' => NULL, 'account_number' => '1010010006', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Capital Work-in-progress - Cost', 'description' => 'Capital Work-in-progress - Cost', 'slug' => 'capital-work-in-progress-cost', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:07', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 7, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 4, 'edited_by' => 2, 'name' => 'Building Improvements - Accumulated Depreciation', 'currency' => NULL, 'account_number' => '1010010007', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Building Improvements - Accumulated Depreciation', 'description' => 'Building Improvements - Accumulated Depreciation', 'slug' => 'building-improvements-accumulated-depreciation', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:07', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 8, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 4, 'edited_by' => 2, 'name' => 'Office Furniture & Fittings - Accumulated Depreciation', 'currency' => NULL, 'account_number' => '1010010008', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Office Furniture & Fittings - Accumulated Depreciation', 'description' => 'Office Furniture & Fittings - Accumulated Depreciation', 'slug' => 'office-furniture-fittings-accumulated-depreciation', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:07', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 9, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 4, 'edited_by' => 2, 'name' => 'Office Equipments - Accumulated Depreciation', 'currency' => NULL, 'account_number' => '1010010009', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Office Equipments - Accumulated Depreciation', 'description' => 'Office Equipments - Accumulated Depreciation', 'slug' => 'office-equipments-accumulated-depreciation', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:07', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 10, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 4, 'edited_by' => 2, 'name' => 'Computer & IT equipments - Accumulated Depreciation', 'currency' => NULL, 'account_number' => '1010010010', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Computer & IT equipments - Accumulated Depreciation', 'description' => 'Computer & IT equipments - Accumulated Depreciation', 'slug' => 'computer-it-equipments-accumulated-depreciation', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:07', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 11, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 4, 'edited_by' => 2, 'name' => 'Motor Vehicle - Accumulated Depreciation', 'currency' => NULL, 'account_number' => '1010010011', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Motor Vehicle - Accumulated Depreciation', 'description' => 'Motor Vehicle - Accumulated Depreciation', 'slug' => 'motor-vehicle-accumulated-depreciation', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:07', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 12, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 6, 'edited_by' => 2, 'name' => 'Softwares', 'currency' => NULL, 'account_number' => '1010030001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Softwares', 'description' => 'Softwares', 'slug' => 'softwares', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:07', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 13, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 6, 'edited_by' => 2, 'name' => 'Softwares - accumulated amortization', 'currency' => NULL, 'account_number' => '1010030002', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Softwares - accumulated amortization', 'description' => 'Softwares - accumulated amortization', 'slug' => 'softwares-accumulated-amortization', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 14, 'account_type_id' => 1, 'account_category_id' => 1, 'account_sub_category_id' => 30, 'edited_by' => 2, 'name' => 'Bank Guarantees', 'currency' => NULL, 'account_number' => '1010040001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Bank Guarantees', 'description' => 'Bank Guarantees', 'slug' => 'bank-guarantees', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 15, 'account_type_id' => 1, 'account_category_id' => 2, 'account_sub_category_id' => 3, 'edited_by' => 2, 'name' => 'Inventories', 'currency' => NULL, 'account_number' => '1020030001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Inventories', 'description' => 'Inventories', 'slug' => 'inventories', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 16, 'account_type_id' => 1, 'account_category_id' => 2, 'account_sub_category_id' => 3, 'edited_by' => 2, 'name' => 'Inventories In-transit', 'currency' => NULL, 'account_number' => '1020030002', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Inventories In-transit', 'description' => 'Inventories In-transit', 'slug' => 'inventories-in-transit', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 17, 'account_type_id' => 1, 'account_category_id' => 2, 'account_sub_category_id' => 25, 'edited_by' => 2, 'name' => 'Prepaid Rent', 'currency' => NULL, 'account_number' => '1020040001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Prepaid Rent', 'description' => 'Prepaid Rent', 'slug' => 'prepaid-rent', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 18, 'account_type_id' => 1, 'account_category_id' => 2, 'account_sub_category_id' => 25, 'edited_by' => 2, 'name' => 'Prepaid Insurance', 'currency' => NULL, 'account_number' => '1020040002', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Prepaid Insurance', 'description' => 'Prepaid Insurance', 'slug' => 'prepaid-insurance', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 19, 'account_type_id' => 1, 'account_category_id' => 2, 'account_sub_category_id' => 25, 'edited_by' => 2, 'name' => 'Other Prepayments', 'currency' => NULL, 'account_number' => '1020040003', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Other Prepayments', 'description' => 'Other Prepayments', 'slug' => 'other-prepayments', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
            ['id' => 20, 'account_type_id' => 1, 'account_category_id' => 2, 'account_sub_category_id' => 1, 'edited_by' => 2, 'name' => 'Supplier Advances', 'currency' => NULL, 'account_number' => '1020010001', 'old_account_number' => '', 'second_leg_account_id' => NULL, 'reference_code' => 'Supplier Advances', 'description' => 'Supplier Advances', 'slug' => 'supplier-advances', 'opening_balance' => '0.00', 'balance_date' => NULL, 'balance' => NULL, 'is_active' => 'true', 'is_default' => 'true', 'is_hidden' => 'false', 'created_at' => '2023-10-11 22:42:08', 'updated_at' => '2024-03-13 14:55:50',  'deleted_at' => NULL, 'company_id' => 2],
        ];

        DB::table('finance_chart_of_accounts')->insert($chartOfAccounts);
    }
}
