<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer Statement</title>
    <link rel="stylesheet" href="styles.css">
</head>

<body>
    <div class="quote-container">
        <table>
            <tr>
                <td>
                    <h2 class="mb-8 h-text">Customer Statement
                    </h2>
                    <p>ID: {{ rand(1000, 9999) }}</p>
                </td>
                <td>
                    <p class="mb-8">Customer ID:
                        <span>{{ $record['customerID'] }}</span>
                    </p>
                    <p class="mb-8">Email: <span>{{ $record['email'] }}</span></p>
                    <p class="mb-8">Generated Date: <span>{{ $record['generated_on'] }}</span>
                    </p>
                </td>
            </tr>
        </table>
    </div>
    <div class="quote-parties">
        <table class="parties-table">
            <tr>
                <td class="from-party">
                    <div class="badge">BookCalc</div>
                    <p class="party-label">Statement Generated By:</p>
                    <p class="party-name company">{{ $record['company']['name'] }}</p>
                    <p style="width: min-content">{{ $record['company']['address'] }}</p>
                </td>
                <td class="to-party">
                    <div class="badge entity">Customer</div>
                    <p class="party-label">Generated For:</p>
                    <p class="party-name company">{{ $record['company_name'] }}</p>
                    <p style="width: min-content">{{ $record['address'] }}</p>
                </td>
            </tr>
        </table>
    </div>
    @if (count($record['invoices']))
        <div class="quote-items">
            <div class="quote-wrapper">
                <h3>Invoices</h3>
                <div>
                    <table>
                        <thead>
                            <tr>
                                <th>InvoiceID</th>
                                <th>Due date</th>
                                <th>Invoice value</th>
                                <th>Amount due</th>
                                <th>Amount paid</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($record['invoices'] as $item)
                                <tr>
                                    <td>{{ $item['invoiceID'] }}</td>
                                    <td>{{ $item['due_date'] }}</td>
                                    <td>{{ $record['currency']['symbol'] }}{{ $item['invoice_value'] }}</td>
                                    <td>{{ $record['currency']['symbol'] }}{{ $item['amount_due'] }}</td>
                                    <td>{{ $record['currency']['symbol'] }}{{ $item['total_amount_paid'] }}</td>
                                    <td>{{ $item['status'] }}</td>
                                </tr>
                                <tr>
                                    <td colspan="3">
                                        <p>Below are the specific item(s) in this invoice as issued</p>
                                        <table>
                                            <thead>
                                                <tr>
                                                    <th>Item detail</th>
                                                    <th>Quantity</th>
                                                    <th>Price</th>
                                                    <th>Discount</th>
                                                    <th>VAT</th>
                                                    <th>Credit amount</th>
                                                    <th>Amount</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @if ($item['line_items'] && count($item['line_items']) > 0)
                                                    @forelse ($item['line_items'] as $line_item)
                                                        <tr>
                                                            <td>{{ $line_item['item_details'] }}</td>
                                                            <td>{{ $line_item['quantity'] }}</td>
                                                            <td>{{ $record['currency']['symbol'] }}{{ $line_item['price'] }}
                                                            </td>
                                                            <td>{{ $line_item['discount'] }}%</td>
                                                            <td>{{ $line_item['vat'] }}%</td>
                                                            <td>{{ $record['currency']['symbol'] }}{{ $line_item['credit_amount'] }}
                                                            </td>
                                                            <td>{{ $record['currency']['symbol'] }}{{ $line_item['amount'] }}
                                                            </td>
                                                        </tr>
                                                    @empty
                                                    @endforelse
                                                @endif
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                            @empty
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    @endif
</body>

</html>
<style>
    * {
        box-sizing: border-box;
        margin: 0;
        padding: 0;
    }

    body {
        font-family: Arial, sans-serif;
        background-color: white;
        color: #667085;
    }

    .h-text {
        color: #344054;
    }

    .mb-8 {
        margin-bottom: 8px;
    }

    .quote-container {
        padding: 30px;
    }

    .quote-header {
        text-align: center;
        margin-bottom: 20px;
    }

    .quote-header h2 {
        color: #555;
        font-size: 24px;
    }

    .quote-header p {
        color: #777;
        font-size: 14px;
        margin: 5px 0;
    }

    .quote-info table {
        width: 100%;
        margin-top: 10px;
    }

    .quote-info td {
        padding: 5px;
        vertical-align: top;
    }

    .due-date {
        color: #8C1823;
    }

    .quote-parties {
        padding: 0px 30px 30px 30px;
    }

    .parties-table {
        width: 100%;
    }

    .from-party,
    .to-party {
        vertical-align: top;
        padding: 10px;
    }

    .badge {
        display: inline-block;
        padding: 5px 10px;
        border-radius: 3px;
        font-size: 14px;
        background: rgba(21, 112, 239, 0.2);
        color: rgba(21, 112, 239, 1);
    }

    .badge.entity {
        background: rgba(105, 56, 239, 0.2);
        color: rgba(105, 56, 239, 1);
    }

    .party-label {
        font-weight: bold;
        margin: 10px 0 5px;
        font-size: 14px;
    }

    .party-name {
        font-size: 16px;
        font-weight: bold;
        color: white;
    }

    .party-name.company {
        background: rgba(21, 112, 239, 1);
        padding: 10px;
        width: fit-content;
        margin-bottom: 14px;
    }

    .party-name.entity {
        background: rgba(105, 56, 239, 1);
        padding: 10px;
        width: fit-content;
        margin-bottom: 14px;
    }

    .quote-items {
        margin: 0px 30px 30px 30px;
        border: 1px solid #d3d3d3;
        border-radius: 8px;
    }

    .quote-wrapper {
        padding: 20px 24px 20px 24px;
    }

    .quote-items h3 {
        font-size: 18px;
        margin-bottom: 5px;
    }

    .quote-items p {
        font-size: 14px;
        color: #777;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 10px;
    }

    thead {
        background-color: #f0f0f0;
    }

    thead th {
        padding: 10px;
        font-size: 14px;
        text-align: left;
    }

    tbody td {
        padding: 10px;
        border-bottom: 1px solid #f0f0f0;
    }

    .quote-summary {
        background: rgba(249, 250, 251, 1);
        padding: 20px;
        margin: 0px 30px 0px 30px;
        border: 1px solid rgba(234, 236, 240, 1);
        border-radius: 8px;
    }

    .summary-table {
        width: 100%;
        margin-top: 20px;
    }

    .summary-table td div.amount {
        text-align: end;
        border: 1px solid rgba(234, 236, 240, 1);
        border-radius: 8px;
        padding: 15px 15px 15px 0;
    }

    .total {
        background: rgba(234, 236, 240, 1);
    }

    .total td {
        font-weight: bold;
        font-size: 18px;
    }

    .total td div {
        background: white;
    }

    .terms {
        margin: 80px 30px 0px 30px;
        padding: 32px 32px 32px 32px;
        background: rgba(249, 250, 251, 1);
        border: 1px solid rgba(234, 236, 240, 1);
        border-radius: 8px;
    }

    .terms p {
        margin-bottom: 10px;
        font-size: 14px;
    }

    textarea {
        width: 100%;
        height: 100px;
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 10px;
        font-size: 14px;
    }
</style>
