name: 🚀 Deploy update on merge to develop
on:
  push:
    branches:
      - develop
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.jkp.mje.mybluehost.me
          username: developer@api.taxtrack.sbscuk.co.uk
          password: ${{ secrets.password }}

      - name: 🔄 Push to master repo
        run: git push repoDamoscky develop
