name: 🚀 Deploy update on merge to develop
on:
  push:
    branches:
      - develop
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.jkp.mje.mybluehost.me
          username: developer@api.taxtrack.sbscuk.co.uk
          password: ${{ secrets.password }}

      - name: Set up authentication for push
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git remote add master_repo https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Damoscky/taxtrack-api.git
          git remote set-url master_repo https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Damoscky/taxtrack-api.git

      # - name: Add master repo as Remote
      #   run: |
      #     git remote add master_repo https://github.com/Damoscky/taxtrack-api.git

      - name: 🔄 Push to master repo
        run: git push master_repo develop
